export const options = {
  form: [ 
  'TWILI',
  'HYLIAN',
  'KEATON',
  'GERUDO',
  'ZORA',
  'KOROK/KOKIRI',
  'GORON',
  'RITO',
  'SHEIKAH',
  'MIXED',
],

  weapon: [ 'Ancient Arrow',
  'Ancient Battle Axe',
  'Ancient Battle Axe+',
  'Ancient Battle Axe++',
  'Ancient Bladesaw',
  'Ancient Bow',
  'Ancient Shield',
  'Ancient Short Sword',
  'Ancient Spear',
  'Arrow',
  'Blizzard Rod',
  'Boat Oar',
  'Boko Bat',
  'Boko Bow',
  'Boko Club',
  'Boko Shield',
  'Boko Spear',
  'Bokoblin Arm',
  'Bomb Arrow',
  'Boomerang',
  'Cobble Crusher',
  'Demon Carver',
  'Double Axe',
  'Dragon Bone Boko Bow',
  'Dragonbone Boko Bat',
  'Dragonbone Boko Club',
  'Dragonbone Boko Shield',
  'Dragonbone Boko Spear',
  'Dragonbone Moblin Club',
  'Dragonbone Moblin Spear',
  'Drillshaft',
  'Duplex Bow',
  'Edge of Duality',
  'Eightfold Blade',
  'Eightfold Longblade',
  'Emblazoned Shield',
  'Enhanced Lizal Spear',
  'Falcon Bow',
  'Farmer\'s Pitchfork',
  'Farming Hoe',
  'Feathered Edge',
  'Feathered Spear',
  'Fire Arrow',
  'Fire Rod',
  'Fisherman\'s Shield',
  'Fishing Harpoon',
  'Flameblade',
  'Flamespear',
  'Forest Dweller\'s Bow',
  'Forest Dweller\'s Shield',
  'Forest Dweller\'s Spear',
  'Forest Dweller\'s Sword',
  'Forked Lizal Spear',
  'Frostblade',
  'Frostspear',
  'Gerudo Scimitar',
  'Gerudo Shield',
  'Gerudo Spear',
  'Giant Boomerang',
  'Golden Bow',
  'Golden Claymore',
  'Great Flameblade',
  'Great Frostblade',
  'Great Thunderblade',
  'Guardian Shield',
  'Guardian Shield+',
  'Guardian Shield++',
  'Guardian Spear',
  'Guardian Spear+',
  'Guardian Spear++',
  'Guardian Sword',
  'Guardian Sword+',
  'Guardian Sword++',
  'Hunter\'s Shield',
  'Ice Arrow',
  'Ice Rod',
  'Iron Sledgehammer',
  'Kite Shield',
  'Knight\'s Bow',
  'Knight\'s Broadsword',
  'Knight\'s Claymore',
  'Knight\'s Halberd',
  'Knight\'s Shield',
  'Korok Leaf',
  'Lightning Rod',
  'Lizal Boomerang',
  'Lizal Bow',
  'Lizal Forked Boomerang',
  'Lizal Shield',
  'Lizal Spear',
  'Lizal Tri-Boomerang',
  'Lizalfos Arm',
  'Lynel Bow',
  'Lynel Crusher',
  'Lynel Shield',
  'Lynel Spear',
  'Lynel Sword',
  'Meteor Rod',
  'Mighty Lynel Bow',
  'Mighty Lynel Crusher',
  'Mighty Lynel Shield',
  'Mighty Lynel Spear',
  'Mighty Lynel Sword',
  'Moblin Arm',
  'Moblin Club',
  'Moblin Spear',
  'Moonlight Scimitar',
  'Phrenic Bow',
  'Pot Lid',
  'Radiant Shield',
  'Reinforced Lizal Shield',
  'Royal Bow',
  'Royal Broadsword',
  'Royal Claymore',
  'Royal Guard\'s Bow',
  'Royal Guard\'s Claymore',
  'Royal Guard\'s Shield',
  'Royal Guard\'s Spear',
  'Royal Guard\'s Sword',
  'Royal Halberd',
  'Royal Shield',
  'Rusty Broadsword',
  'Rusty Claymore',
  'Rusty Halberd',
  'Rusty Shield',
  'Savage Lynel Bow',
  'Savage Lynel Crusher',
  'Savage Lynel Shield',
  'Savage Lynel Spear',
  'Savage Lynel Sword',
  'Sea-Breeze Boomerang',
  'Serpentine Spear',
  'Shield of the Mind\'s Eye',
  'Shock Arrow',
  'Silver Bow',
  'Silver Longsword',
  'Silver Shield',
  'Silverscale Spear',
  'Soldier\'s Bow',
  'Soldier\'s Broadsword',
  'Soldier\'s Claymore',
  'Soldier\'s Shield',
  'Soldier\'s Spear',
  'Soup Ladle',
  'Spiked Boko Bat',
  'Spiked Boko Bow',
  'Spiked Boko Club',
  'Spiked Boko Shield',
  'Spiked Boko Spear',
  'Spiked Moblin Club',
  'Spiked Moblin Spear',
  'Spring-Loaded Hammer',
  'Steel Lizal Bow',
  'Steel Lizal Shield',
  'Stone Smasher',
  'Strengthened Lizal Bow',
  'Swallow Bow',
  'Sword',
  'Throwing Spear',
  'Thunderblade',
  'Thunderspear',
  'Thunderstorm Rod',
  'Torch',
  'Traveler\'s Bow',
  'Traveler\'s Claymore',
  'Traveler\'s Shield',
  'Traveler\'s Spear',
  'Traveler\'s Sword',
  'Tree Branch',
  'Vicious Sickle',
  'Windcleaver',
  'Woodcutter\'s Axe',
  'Wooden Bow',
  'Wooden Mop',
  'Wooden Shield',
  'Zora Spear',
  'Zora Sword',
  ],

  element: [ 
  'DARK',
  'EARTH',
  'ELECTRICITY',
  'ENERGY',
  'FIRE',
  'ICE',
  'LIGHT',
  'METAL',
  'ROCK',
  'STEEL',
  'TIME',
  'WATER',
  'WIND',
  'WOOD', 
],

  animal: [ 'Horse',
  'Giant Horse',
  'White Horse',
  'Lord of the Mountain',
  'Stalhorse',
  'Donkey',
  'Sand Seal',
  'Bushy-Tailed Squirrel',
  'Woodland Boar',
  'Red-Tusked Boar',
  'Mountain Goat',
  'White Goat',
  'Mountain Buck',
  'Mountain Doe',
  'Water Buffalo',
  'Hateno Cow',
  'Highland Sheep',
  'Grassland Fox',
  'Snowcoat Fox',
  'Maraudo Wolf',
  'Wasteland Coyote',
  'Cold-Footed Wolf',
  'Tabantha Moose',
  'Great-Horned Rhinoceros',
  'Honeyvore Bear',
  'Grizzlemaw Bear',
  'Hylian Retriever',
  'Blupee',
  'Common Sparrow',
  'Red Sparrow',
  'Blue Sparrow',
  'Rainbow Sapprow',
  'Sand Sparrow',
  'Golden Sparrow',
  'Wood Pigeon',
  'Rainbow Pigeon',
  'Hotfeather Pigeon',
  'White Pigeon',
  'Mountain Crow',
  'Bright-Chested Duck',
  'Blue-Winged Heron',
  'Pink Heron',
  'Islander Hawk',
  'Seagull',
  'Eldin Ostrich',
  'Cucco',
  'Hyrule Bass',
  'Hearty Bass',
  'Staminoka Bass',
  'Hearty Salmon',
  'Chillfin Trout',
  'Sizzlefin Trout',
  'Voltfin Trout',
  'Stealthfin Trout',
  'Mighty Carp',
  'Armored Carp',
  'Sanke Carp',
  'Mighty Porgy',
  'Armored Porgy',
  'Sneaky River Snail',
  'Hearty Blueshell Snail',
  'Razorclaw Crab',
  'Ironshell Crab',
  'Bright-Eyed Crab',
  'Fairy',
  'Winterwing Butterfly',
  'Summerwing Butterfly',
  'Thunderwing Butterfly',
  'Smotherwing Butterfly',
  'Cold Darner',
  'Warm Darner',
  'Electric Darner',
  'Restless Cricket',
  'Bladed Rhino Beetle',
  'Rugged Rhino Beetle',
  'Energetic Rhino Beetle',
  'Sunset Firefly',
  'Hot-Footed Frog',
  'Tireless Frog',
  'Hightail Lizard',
  'Hearty Lizard',
  'Fireproof Lizard',
  ],

  specialBodyPart: [ '3RD EYE',
  'ARMS',
  'BLOOD',
  'BONE',
  'EARS',
  'EYES',
  'HAIR',
  'HANDS',
  'HORNS',
  'LEGS',
  'MOUTH',
  'NOSE',
  'TAIL',
  'TEETH',
 ],
  
  occupation: [ 'Teacher ',
  'Scholar ',
  'Priest ',
  'Fortune Teller',
  'Witch ',
  'Weaver',
  'Researcher  ',
  'Mask Maker',
  'Craftsman ',
  'Cook ',
  'Blacksmith ',
  'Artist ',
  'Healer ',
  'Courier',
  'Performer  ',
  'Minstrel ',
  'Miner ',
  'Forager ',
  'Fisherman',
  'Farmer',
  'Beekeeper',
  'Animal Breeder ',
  'Hunter ',
  'Herbalist ',
  'Scout ',
  'Mercenary  ',
  'Guard ',
  'Graveskeeper ',
  'Adventurer ',
  'Stablehand',
  'Villager ',
  'Bandit ',
  'Shopkeeper',
  'Merchant ',
  ],

  location:[ 'Rudania\'s Farmlands',
  'Eldin Mines',
  'Volga Forge',
  'Akkala Parade Grounds',
  'Rudania\'s Graveyard',
  'Rudania\'s Hot Springs',
  'Rudania\'s Outskirts',
  'Lake Akkala',
  'Cephla Lake',
  'Rudania\'s Farmer\'s Market',
  'Rudania\'s Trade Shop',
  'Rudania\'s Rock Shop',
  'Rudania\'s Stables',
  'Inariko\'s Dragon\'s Gate',
  'Inariko\'s Forest',
  'Lanayru Promenade',
  'Nayru Statue Waterwheel',
  'Inariko\'s Library',
  'Inariko\'s Graveyard',
  'Inariko\'s Outskirts',
  'Inariko\'s Research Lab',
  'Inariko\'s Farmer\'s Market',
  'Inariko\'s Trade Shop',
  'Inariko\'s Fish Market',
  'Inariko\'s Stables',
  'Inariko\'s Snowfield',
  'Vhintl\'s Skulltula Pass',
  'Vhintl\'s Damel Forest',
  'Vhintl\'s House of Masks',
  'Vhintl\'s Dragon Head Cavern',
  'Vhintl\'s Outskirts',
  'Vhintl\'s Graveyard',
  'Vhintl\'s Walkways',
  'Vhintl\'s Ziplines',
  'Vhintl\'s Farmer\'s Market',
  'Vhintl\'s Trade Shop',
  'Vhintl\'s Stables',
  ],

  misc: [ 'ANCIENTS',
  'BEAD',
  'BELLS',
  'BOOK',
  'BOOTS',
  'BUBBLES',
  'CACTUS',
  'CANDLES',
  'CARDS',
  'CASTLE',
  'CLOUDS',
  'COMET',
  'CORAL',
  'CRYSTAL',
  'DUST',
  'FEATHER',
  'GALAXY',
  'GAMBLING',
  'GLITCH',
  'HALO',
  'ILLUSION',
  'LAVA',
  'LUCK',
  'MAGIC',
  'MAGIC BANDAGES',
  'MAGIC CLOAK',
  'MASK',
  'MAZE',
  'MIRAGE',
  'MIRROR',
  'MONEY',
  'MOON',
  'MOSS',
  'MUSHROOM',
  'NECROMANCY',
  'NEEDLE',
  'NOSE BLEED',
  'OCEAN',
  'ORIGAMI',
  'PANDORAS BOX',
  'PAPER',
  'PARAGON',
  'PETRIFICATION',
  'PHOBIA',
  'PLANET',
  'PLANT',
  'POLLEN',
  'PUZZLE',
  'RAIN',
  'REGAL',
  'RELIC',
  'RIBBON',
  'ROOT',
  'ROOT',
  'RUINS',
  'RUNES',
  'SACRED',
  'SAND',
  'SANDMAN',
  'SCALES',
  'SCAR',
  'SCARF',
  'SCROLL',
  'SEA',
  'SHRINE',
  'SIGIL',
  'SIN',
  'SKY',
  'SLEEP',
  'SMOKE',
  'SNOW',
  'SOUL',
  'SOUL SEWER',
  'SOUL SNAKE',
  'SPELL',
  'STAR',
  'STITCH',
  'STONE',
  'STRING',
  'STUFFED ANIMALS',
  'SUMMON',
  'SUN',
  'TALISMAN',
  'TAROT',
  'TATTOO',
  'TEARS',
  'TOXIC',
  'UMBRELLA',
  'VINES',
  'VIRTUES',
  'VOICE',
  'WEAPON SHIFTER',
  'WINER MAKER',
  'ZIPPERS',
  ],

 
  posPersonality: [ 'ACCESSIBLE',
  'ACTIVE',
  'ADAPTABLE',
  'ADMIRABLE',
  'ADVENTUROUS',
  'AGREEABLE',
  'ALERT',
  'ALLOCENTRIC',
  'ATTRACTIVE',
  'BALANCED',
  'BENEVOLENT',
  'BRILLIANT',
  'CALM',
  'CAPABLE',
  'CAPTIVATING',
  'CARING',
  'CHALLENGING',
  'CHARISMATIC',
  'CHARMING',
  'CHEERFUL',
  'CLEAN',
  'CLEAR-HEADED',
  'CLEVER',
  'COLORFUL',
  'COMPANIONLY',
  'COMPASSIONATE',
  'CONCILIATORY',
  'CONFIDENT',
  'CONSCIENTIOUS',
  'CONSIDERATE',
  'CONSTANT',
  'CONTEMPLATIVE',
  'COOPERATIVE',
  'COURAGEOUS',
  'COURTEOUS',
  'CREATIVE',
  'CULTURED',
  'CURIOUS',
  'DARING',
  'DEBONAIR',
  'DECENT',
  'DECISIVE',
  'DEDICATED',
  'DEEP',
  'DIGNIFIED',
  'DIRECTED',
  'DISCIPLINED',
  'DISCREET',
  'DRAMATIC',
  'DUTIFUL',
  'DYNAMIC',
  'EARNEST',
  'EBULLIENT',
  'EDUCATED',
  'EFFICIENT',
  'ELEGANT',
  'ELOQUENT',
  'EMPATHETIC',
  'ENERGETIC',
  'ENTHUSIASTIC',
  'ESTHETIC',
  'EXCITING',
  'EXTRAORDINARY',
  'FAIR',
  'FAITHFUL',
  'FARSIGHTED',
  'FELICIFIC',
  'FIRM',
  'FLEXIBLE',
  'FOCUSED',
  'FORECFUL',
  'FORGIVING',
  'FORTHRIGHT',
  'FREETHINKING',
  'FRIENDLY',
  'FUN-LOVING',
  'GALLANT',
  'GENEROUS',
  'GENTLE',
  'GENUINE',
  'GOOD-NATURED',
  'GRACIOUS',
  'HARDWORKING',
  'HEALTHY',
  'HEARTY',
  'HELPFUL',
  'HERIOC',
  'HIGH-MINDED',
  'HONEST',
  'HONORABLE',
  'HUMBLE',
  'HUMOROUS',
  'IDEALISTIC',
  'IMAGINATIVE',
  'IMPRESSIVE',
  'INCISIVE',
  'INCORRUPTIBLE',
  'INDEPENDENT',
  'INDIVIDUALISTIC',
  'INNOVATIVE',
  'INOFFENSIVE',
  'INSIGHTFUL',
  'INSOUCIANT',
  'INTELLIGENT',
  'INTUITIVE',
  'INVULNERABLE',
  'KIND',
  'KNOWLEDGE',
  'LEADERLY',
  'LEISURELY',
  'LIBERAL',
  'LOGICAL',
  'LOVABLE',
  'LOYAL',
  'LYRICAL',
  'MAGNANIMOUS',
  'MANY-SIDED',
  'MASCULINE (MANLY)',
  'MATICULOUS',
  'MATURE',
  'METHODICAL',
  'MODERATE',
  'MODEST',
  'MULTI-LEVELED',
  'NEAT',
  'NONAUTHORITARIAN',
  'OBJECTIVE',
  'OBSERVANT',
  'OPEN',
  'OPTIMISTIC',
  'ORDERLY',
  'ORGANIZED',
  'ORIGINAL',
  'PAINSTAKING',
  'PASSIONATE',
  'PATIENT',
  'PATRIOTIC',
  'PEACEFUL',
  'PERCEPTIVE',
  'PERFECTIONIST',
  'PERSONABLE',
  'PERSUASIVE',
  'PLANFUL',
  'PLAYFUL',
  'POLISHED',
  'POPULAR',
  'PRACTICAL',
  'PRECISE',
  'PRINCIPLED',
  'PROFOUND',
  'PROTEAN',
  'PROTECTIVE',
  'PROVIDENTIAL',
  'PRUDENT',
  'PRUPOSEFUL',
  'PUNCTUAL',
  'RATIONAL',
  'REALISTIC',
  'REFLECTIVE',
  'RELAXED',
  'RELIABLE',
  'RESOURCEFUL',
  'RESPECTFUL',
  'RESPONSIBLE',
  'RESPONSIVE',
  'REVERENTIAL',
  'ROMANTIC',
  'RUSTIC',
  'SAGE',
  'SANE',
  'SCHOLARLY',
  'SCRUPULOUS',
  'SECURE',
  'SELF-CRITICAL',
  'SELF-DEFACING',
  'SELF-DENYING',
  'SELF-RELIANT',
  'SELF-SUFFICENT',
  'SELFLESS',
  'SENSITIVE',
  'SENTIMENTAL',
  'SERAPHIC',
  'SERIOUS',
  'SEXY',
  'SHARING',
  'SHREWD',
  'SIMPLE',
  'SKILLFUL',
  'SOBER',
  'SOCIABLE',
  'SOLID',
  'SOPHISTICATED',
  'SPONTANEOUS',
  'SPORTING',
  'STABLE',
  'STEADFAST',
  'STEADY',
  'STOIC',
  'STRONG',
  'STUDIOUS',
  'SUAVE',
  'SUBTLE',
  'SWEET',
  'SYMPATHETIC',
  'SYSTEMATIC',
  'TASTEFUL',
  'TEACHERLY',
  'THOROUGH',
  'TIDY',
  'TOLERANT',
  'TRACTABLE',
  'TRUSTING',
  'UNCOMPLAINING',
  'UNDERSTANDING',
  'UNDOGMATIC',
  'UNFOOLABLE',
  'UPRIGHT',
  'URBANE',
  'VENTURESOME',
  'VIVACIOUS',
  'WARM',
  'WELL-BRED',
  'WELL-READ',
  'WELL-ROUNDED',
  'WINNING',
  'WISE',
  'WITTY',
  'YOUTHFUL',
  ],

  nuePersonality: [
    "ABSENTMINDED",
    "AGGRESSIVE",
    "AMBITIOUS",
    "AMUSING",
    "ARTFUL",
    "ASCETIC",
    "AUTHORITARIAN",
    "BIG-THINKING",
    "CHUMMY",
    "CIRCUMSPECT",
    "COMPETITIVE",
    "COMPLEX",
    "CONFIDENTIAL",
    "CONSERVATIVE",
    "CONTRADICTORY",
    "CRISP",
    "CUTE",
    "DECEPTIVE",
    "DETERMINED",
    "DOMINATING",
    "DREAMY",
    "DRIVING",
    "DROLL",
    "DRY",
    "EARTHY",
    "EFFEMINATE",
    "EMOTIONAL",
    "ENIGMATIC",
    "EXPERIMENTAL",
    "FAMILIAL",
    "FOLKSY",
    "FORMAL",
    "FREEWHEELING",
    "FRUGAL",
    "GLAMOROUS",
    "GUILELESS",
    "HIGH-SPIRITED",
    "HURIED",
    "HYPNOTIC",
    "ICONOCLASTIC",
    "IDIOSYNCRATIC",
    "IMPASSIVE",
    "IMPERSONAL",
    "IMPRESSIONABLE",
    "INTENSE",
    "INVISIBLE",
    "IRRELIGIOUS",
    "IRREVERENT",
    "MATERNAL",
    "MELLOW",
    "MODERN",
    "MORALISTIC",
    "MYSTICAL",
    "NEUTRAL",
    "NONCOMMITTAL",
    "NONCOMPETITIVE",
    "OBEDIENT",
    "OLD-FASHINED",
    "ORDINARY",
    "OUTSPOKEN",
    "PATERNALISTIC",
    "PHYSICAL",
    "PLACID",
    "POLITICAL",
    "PREDICTABLE",
    "PREOCCUPIED",
    "PRIVATE",
    "PROGRESSIVE",
    "PROUD",
    "PURE",
    "QUESTIONING",
    "QUIET",
    "RELIGIOUS",
    "RESERVED",
    "RESTRAINED",
    "RETIRING",
    "SARCASTIC",
    "SELF-CONSCIOUS",
    "SENSUAL",
    "SKEPTICAL",
    "SMOOTH",
    "SOFT",
    "SOLEMN",
    "SOLITARY",
    "STERN",
    "STOIID",
    "STRICT",
    "STUBBORN",
    "STYLISH",
    "SUBJECTIVE",
    "SURPRISING",
    "SOFT",
    "TOUGH",
    "UNAGGRESSIVE",
    "UNAMBITIOUS",
    "UNCEREMONIOUS",
    "UNCHANGING",
    "UNDEMANDING",
    "UNFATHOMABLE",
    "UNHURRIED",
    "UNINHIBITED",
    "UNPATRIOTIC",
    "UNPREDICATABLE",
    "UNRELIGIOUS",
    "UNSENTIMENTAL",
    "WHIMSICAL",
  ],
  negPersonality: [
    "ABRASIVE",
    "ABRUPT",
    "AGONIZING",
    "AIMLESS",
    "AIRY",
    "ALOOF",
    "AMORAL",
    "ANGRY",
    "ASOCIAL",
    "ASSERTIVE",
    "ASTIGMATIC",
    "BARBARIC",
    "BEWILDERED",
    "BIZARRE",
    "BLAND",
    "BLUNT",
    "BIOSTEROUS",
    "BRITTLE",
    "BRUTAL",
    "CALCULATING",
    "CALLOUS",
    "CANTAKEROUS",
    "CARELESS",
    "CAUTIOUS",
    "CHARMLESS",
    "CHILDISH",
    "CLUMSY",
    "COARSE",
    "COLD",
    "COLORLESS",
    "COMPLACENT",
    "COMPLAINTIVE",
    "COMPULSIVE",
    "CONCEITED",
    "CONDEMNATORY",
    "CONFORMIST",
    "CONFUSED",
    "CONTEMPTIBLE",
    "CONVENTIONAL",
    "COWARDLY",
    "CRAFTY",
    "CRASS",
    "CRAZY",
    "CRIMINAL",
    "CRITICAL",
    "CRUDE",
    "CRUEL",
    "CYNICAL",
    "DECADENT",
    "DECEITFUL",
    "DELICATE",
    "DEMANDING",
    "DEPENDENT",
    "DESPERATE",
    "DESTRUCTIVE",
    "DEVIOUS",
    "DIFFICULT",
    "DIRTY",
    "DISCONCERTING",
    "DISCONTENTED",
    "DISCOURAGING",
    "DISCOURTEOUS",
    "DISHONEST",
    "DISLOYAL",
    "DISOBEDIENT",
    "DISORDERLY",
    "DISORGANIZED",
    "DISPUTATIOUS",
    "DISRESPECTFUL",
    "DISRUPTIVE",
    "DISSOLUTE",
    "DISSONANT",
    "DISTRACTIBLE",
    "DISTURBING",
    "DOGMATIC",
    "DOMINEERING",
    "DULL",
    "EASILY DISCOURAGED",
    "EGOCENTRIC",
    "ENERVATED",
    "ENVIOUS",
    "ERRATIC",
    "ESCAPIST",
    "EXCITABLE",
    "EXPEDIENT",
    "EXTRAVAGANT",
    "EXTREME",
    "FAITHLESS",
    "FALSE",
    "FANATICAL",
    "FANCIFUL",
    "FATALISTIC",
    "FAWNING",
    "FEARFUL",
    "FICKLE",
    "FIERY",
    "FIXED",
    "FLAMBOYANT",
    "FOOLISH",
    "FORGETFUL",
    "FRAUDULENT",
    "FRIGHTENING",
    "FRIVOLOUS",
    "GLOOMY",
    "GRACELESS",
    "GRAND",
    "GREEDY",
    "GRIM",
    "GULLIBLE",
    "HATEFUL",
    "HAUGHTY",
    "HEDONISTIC",
    "HESITANT",
    "HIDEBOUND",
    "HIGH-HANDED",
    "HOSTILE",
    "IGNORANT",
    "IMITATIVE",
    "IMPATIENT",
    "IMPRACTICAL",
    "IMPRUDENT",
    "IMPULSIVE",
    "INCONSIDERATE",
    "INCURIOUS",
    "INDECISIVE",
    "INDULGENT",
    "INERT",
    "INHIBITED",
    "INSECURE",
    "INSENSITIVE",
    "INSINCERE",
    "INSULTING",
    "INTOLERANT",
    "IRASCIBLE",
    "IRRATIONAL",
    "IRRESPONSIBLE",
    "IRRITABLE",
    "LAZY",
    "LIBIDINOUS",
    "LOQUACIOUS",
    "MALICIOUS",
    "MANNERED",
    "MANNERLESS",
    "MAWKISH",
    "MEALYMOUTHED",
    "MECHANICAL",
    "MEDDLESOME",
    "MELANCHOLIC",
    "MERETRICIOUS",
    "MESSY",
    "MISERABLE",
    "MISERLY",
    "MISGUIDED",
    "MISTAKEN",
    "MONEY-MINDED",
    "MONSTROUS",
    "MOODY",
    "MORBID",
    "MUDDLE-HEADED",
    "NAIVE",
    "NARCISSISTIC",
    "NARROW",
    "NARROW-MINDED",
    "NATTY",
    "NEGATIVISTIC",
    "NEGLECTFUL",
    "NEUROTIC",
    "NIHILISTIC",
    "OBNOXIOUS",
    "OBSESSIVE",
    "OBVIOUS",
    "ODD",
    "OFFHAND",
    "ONE-DIMENSIONAL",
    "ONE-SIDED",
    "OPINIONATED",
    "OPPORTUNISTIC",
    "OPPRESSED",
    "OUTRAGEOUS",
    "OVERIMAGINATIVE",
    "PARANOID",
    "PASSIVE",
    "PEDANTIC",
    "PERVERSE",
    "PETTY",
    "PHARISSICAL",
    "PHLEGMATIC",
    "PLODDING",
    "POMPOUS",
    "POSSESSIVE",
    "POWER-HUNGRY",
    "PREDATORY",
    "PREJUDICED",
    "PRESUMPTUOUS",
    "PRETENTIOUS",
    "PRIM",
    "PROCRASTINATING",
    "PROFLIGATE",
    "PROVOCATIVE",
    "PUGNACIOUS",
    "PURITANICAL",
    "QUIRKY",
    "REACTIONARY",
    "REACTIVE",
    "REGIMENTAL",
    "REGRETFUL",
    "REPENTANT",
    "REPRESSED",
    "RESENTFUL",
    "RIDICULOUS",
    "RIGID",
    "RITUALISTIC",
    "ROWDY",
    "RUINED",
    "SADISTIC",
    "SANCTIMONIOUS",
    "SCHEMING",
    "SCORNFUL",
    "SECRETIVE",
    "SEDENTARY",
    "SELFISH",
    "SELF-INDULGENT",
    "SHALLOW",
    "SHORTSIGHTED",
    "SHY",
    "SILLY",
    "SINGLE-MINDED",
    "SLOPPY",
    "SLOW",
    "SLY",
    "SMALL-THINKING",
    "SOFTHEADED",
    "SORDID",
    "STEELY",
    "STIFF",
    "STRONG-WILLED",
    "STUPID",
    "SUBMISSIVE",
    "SUPERFICIAL",
    "SUPERSTITIOUS",
    "SUSPICIOUS",
    "TACTLESS",
    "TASTELESS",
    "TENSE",
    "THIEVISH",
    "THOUGHTLESS",
    "TIMID",
    "TRANSPARENT",
    "TREACHEROUS",
    "TRENDY",
    "TROUBLESOME",
    "UNAPPRECIATIVE",
    "UNCARING",
    "UNCHARITABLE",
    "UNCONVINCING",
    "UNCOOPERATIVE",
    "UNCREATIVE",
    "UNCRITICAL",
    "UNCTUOUS",
    "UNDISCIPLINED",
    "UNFRIENDLY",
    "UNGRATEFUL",
    "UNHEALTHY",
    "UNIMAGINATIVE",
    "UNIMPRESSIVE",
    "UNLOVABLE",
    "UNPOLISHED",
    "UNPRINCIPLED",
    "UNREALISTIC",
    "UNREFLECTIVE",
    "UNRELIABLE",
    "UNRESTRAINED",
    "UNSELF-CRITICAL",
    "UNSTABLE",
    "VACUOUS",
    "VAGUE",
    "VENAL",
    "VENOMOUS",
    "VINDICTIVE",
    "VULNERABLE",
    "WEAK",
    "WEAK-WILLED",
    "WELL-MEANING",
    "WILLFUL",
    "WISHFUL",
    "ZANY",
  ],
  trope: [ 'ABSENT FATHER',
  'ABSENT-MINDED PROFESSOR',
  'ACTION HERO',
  'ADDICT',
  'AMBITIOUS QUEEN',
  'AMSEL IN DISTRESS',
  'ANGRY CHEF',
  'ANNOYING NEIGHBOR',
  'ANTI-HERO',
  'AUTHOR SURROGATE',
  'AUTHORITY FIGURE',
  'BACKSTABBING FRIEND',
  'BAD BOY',
  'BAD FRIEND',
  'BARD',
  'BATTLE-AXE',
  'BEATNIK',
  'BELIEVER',
  'BENEVOLENT RULER',
  'BESTERMAN',
  'BITTER WAR VETERAN',
  'BLACK KNIGHT',
  'BLIND SEER',
  'BOSS',
  'BOY NEXT DOOR',
  'BRAGGART',
  'BRAINS AND BRAWN',
  'BRUCE LEE CLONE',
  'BUG-EYED MONSTER',
  'BULLY',
  'BUMBLING SIDEKICK',
  'BUREAUCRAT',
  'BYRONIC HERO',
  'BYRONIC/TORTURED HERO',
  'CAREER CRIMINAL',
  'CARETAKER',
  'CAT LADY',
  'CATALYST',
  'CHILD SAVIOUR',
  'CHILDHOOD FRIEND',
  'CHOOSER OF THE CHOSEN ONE',
  'CHOSEN ONE',
  'CHRIST-FIGURE',
  'CHUUNIBYOU',
  'CINDERELLA TYPE',
  'CLASS CLOWN',
  'COMIC RELIEF',
  'COMPETENT MAN',
  'COMPLICATED PAST',
  'CON ARTIST',
  'CONTENDER',
  'COUSIN OLIVER',
  'COWARD',
  'CRAZY CAT LADY',
  'CREEPY TWINS',
  'CRONE',
  'CURMUDGEON',
  'DAMSEL IN DISTRESS',
  'DANDERE',
  'DANDY',
  'DARK JESTER',
  'DARK LADY',
  'DARK LORD',
  'DASTARDLY WHIPLASH',
  'DEFORMED',
  'DEREDERE',
  'DEVIL INCARNATE/ DARK LORD',
  'DEVOTEE',
  'DIVORCED DAD',
  'DONOR',
  'DOPPELGÄNGER',
  'DOUBLE AGENT',
  'DRAGON LADY',
  'DREAMER',
  'DRILL SERGEANT',
  'DUMB BLONDE',
  'DUMB COLLEGE STUDENT',
  'DUMB MUSCLE',
  'EASY ADAPTER',
  'ECCENTRIC FOREIGNER',
  'EL BANDIDO',
  'ELDERLY MARTIAL ARTS MASTER',
  'ELDERLY MASTER',
  'EMOTIONALLY REPRESSED',
  'EMPATH',
  'ENABLER',
  'ETERNAL KLUTZ',
  'EVERYMAN/WOMAN',
  'EVIL CLOWN',
  'EVIL MATRIARCH',
  'EVIL TWIN',
  'EXPERIMENT GONE WRONG',
  'EXPLORER',
  'FALL GUY',
  'FALLEN/ CORRUPTER',
  'FARMER\'S DAUGHTER',
  'FARMER\'S WIFE',
  'FEMALE CLOWN',
  'FEMME FATALE',
  'FINAL GIRL',
  'FOIL',
  'FOLK HERO',
  'FOOL',
  'FOP',
  'FRENCH MAID',
  'FRIENDLY RIVAL',
  'GAY BEST FRIEND',
  'GEEK',
  'GENERIC AUDIENCE STAND-IN',
  'GENERIC HORROR GIRL',
  'GENERIC SLASHER',
  'GENIUS',
  'GENTLE GIANT',
  'GENTLEMAN THIEF',
  'GIFTED CHILD',
  'GIRL NEXT DOOR',
  'GOD/ GODDESS',
  'GOOD GUY/TRADITIONAL HERO',
  'GOOD SAMARITAN',
  'GOOD TIME TRAVELER',
  'GRACIOSO',
  'GRANDE DAME',
  'GRIEVING WIDOW',
  'GROTESQUE',
  'GROUPIE',
  'GUARDIAN GRANDPARENTS',
  'GUIDE',
  'GUNG-HO AMERICAN',
  'HAG',
  'HALFBREED HARLOT',
  'HARD-BOILED DETECTIVE',
  'HARDWORKER',
  'HARLEQUIN',
  'HARSH JUDGE',
  'HEDONIST',
  'HERMIT',
  'HIMBO/BIMBO',
  'HIME/OUJI DERE',
  'HIPPY',
  'HOLMESIAN DETECTIVE',
  'HOOKER WITH A HEART OF GOLD',
  'HOPELESS ROMANTIC',
  'HOTSHOT',
  'HOUSEWIFE',
  'HUMAN PLOT DEVICE',
  'HUMAN-LIKE CREATURE',
  'HUNCHBACK',
  'IDIOT',
  'IDIOT SAVANT',
  'IDIOT TURNED HERO',
  'IMMIGRANT',
  'IMPOSTER/PRETENDER',
  'INCOMPETENT OFFICER',
  'INGENUE',
  'INNOCENT',
  'INNOVATOR',
  'INVASIVE NEIGHBOR',
  'JADED LEAD',
  'JEWISH MOTHER',
  'JOCK',
  'JOKER/ JESTER',
  'JOURNALIST',
  'KAMIDERE',
  'KEYSTONE KOP',
  'KNIGHT-ERRANT',
  'KUUDERE',
  'LATIN LOVER',
  'LEADER',
  'LEGACY HERO',
  'LIAM NEESON TYPE',
  'LIAR',
  'LITTLE GREEN MEN',
  'LIVING LEGEND',
  'LOATHLY LADY',
  'LOGICIAN',
  'LONER',
  'LOOSE CANNON/CROOKED COP',
  'LOVABLE LOSER',
  'LOVABLE PERVERT',
  'LOVE INTEREST',
  'LOVERS',
  'MACHIAVELLE',
  'MACHO ACTION GUY',
  'MAD SCIENTIST',
  'MAGICAL NEGRO',
  'MAGICIAN/MAGE/SHAMAN',
  'MAIDEN',
  'MALE BUFFOON',
  'MALEWIFE',
  'MAN ALONE',
  'MANIC PIXIE DREAM GIRL',
  'MARTYR',
  'MARY SUE',
  'MASKED SUPERHERO',
  'MASOCHIST',
  'MAVERICK',
  'MEAN POPULAR GIRL',
  'MENTOR',
  'MESSENGER',
  'MESSIAH',
  'MIDDLE CHILD',
  'MILES GLORIOSUS',
  'MILKMAN',
  'MILTONIC HERO',
  'MOMMA’S BOY',
  'MONK',
  'MONSTER',
  'MOTHER-IN-LAW',
  'MOTHER\'S BOY',
  'MOTHER/MATRIARCH',
  'MR. FIX IT',
  'MYTHOLOGICAL KING',
  'NAPOLEONIC VILLAIN',
  'NARRATOR',
  'NATURE LOVER',
  'NEMESIS',
  'NERD',
  'NICE GUY',
  'NOBLE SAVAGE',
  'NON-CONFORMIST',
  'OUT-OF-TOWNER',
  'OUTCAST',
  'OUTLAW',
  'OVERLY PATIENT WIFE',
  'PANTOMIME DAME',
  'PARANOID CONSPIRACY THEORIST',
  'PATRIARCH',
  'PAUL LYNDE TYPE',
  'PEACEMAKER',
  'PERFECTIONIST',
  'PERPETUAL TRAVELER',
  'PETRUSHKA',
  'PHILOSOPHER',
  'PIERROT',
  'PINNING FRIEND',
  'PIRATE',
  'PREDATOR',
  'PREPPY',
  'PREY',
  'PRINCE CHARMING',
  'PRINCE ON A WHITE HORSE',
  'PRINCESSE LOINTAINE',
  'PSYCHO-BIDDY',
  'PSYCHOPATH',
  'PUPPETEER',
  'RAGS TO RICHES',
  'RAW RECRUIT',
  'REBEL',
  'REDNECK',
  'REDSHIRT',
  'RELUCTANT HERO',
  'RELUCTANT/UNWILLING MONSTER',
  'RICH WOMAN',
  'RIGHTFUL HEIR',
  'RIGHTFUL KING',
  'ROBIN HOOD',
  'ROMANTIC RUNNER-UP',
  'ROYAL USURPER',
  'SAVANT',
  'SCAPEGOAT',
  'SCHOOLMA\'AM',
  'SCROOGE',
  'SECRETIVE',
  'SENEX AMANS',
  'SENEX IRATUS',
  'SERVANT/SLAVE',
  'SEXY GRANDMA',
  'SHAPESHIFTER',
  'SHERLOCK HOLMES TYPE',
  'SHREW',
  'SICKLY',
  'SIDEKICK',
  'SINNEKINS',
  'SISSY',
  'SKEPTIC',
  'SLEAZY LAWYER',
  'SLEAZY POLITICIAN',
  'SLOW BURN',
  'SOUBRETTE',
  'SOUTHERN BELLE',
  'SPEAR CARRIER',
  'STAND-IN PARENT/ROLE MODEL',
  'STAR-CROSSED LOVERS',
  'STARVING ARTIST',
  'STRAIGHT MAN',
  'STUDENT',
  'STUPID MUSCLE',
  'SUCCUBUS',
  'SUPER SOLDIER',
  'SUPERFLUOUS MAN',
  'SUPERHERO',
  'SUPERSOLDIER',
  'SUPERVILLAIN',
  'SURFER',
  'SURPRISE GENIUS',
  'SURVIVALIST',
  'SURVIVOR',
  'SWASHBUCKLER',
  'THE CHOSEN ONE',
  'THRILL-SEEKER',
  'THUG',
  'TIGER MOM',
  'TIME POLICE',
  'TIME TRAVELER’S WIFE',
  'TOKEN BLACK CHARACTER',
  'TOMBOY',
  'TORTURED ARTIST',
  'TORTURED SUPERHERO',
  'TOWN DRUNK',
  'TRADITIONALIST',
  'TRAGIC HERO',
  'TRAGIC MULATTO',
  'TRICKSTER',
  'TRICKY SLAVE',
  'TROUBLED TEENAGER',
  'TROUBLED VET',
  'TRUSTY SIDEKICK',
  'TRUTH SEEKER',
  'TSUNDERE',
  'TURNCOAT',
  'TYRANT',
  'ÜBERMENSCH',
  'UNDERLING/HENCHMAN',
  'UNFORTUNATE ORPHAN',
  'UNKNOWN THREAT',
  'UNLIKELY HERO',
  'UNSEEN CHARACTER',
  'VAMP',
  'VAMPIRE',
  'VICE',
  'VIGILANTE',
  'VILLAGE IDIOT',
  'VILLAIN',
  'VISIONARY',
  'WANNABE HERO',
  'WARRIOR',
  'WELL-INTENTIONED EXTREMIST',
  'WHISKEY PRIEST',
  'WHITE FRIEND',
  'WHITE HUNTER',
  'WICKED STEPMOTHER',
  'WICKED WITCH',
  'WIMP',
  'WISE FOOL',
  'WISE MENTOR',
  'WISE OLD MAN',
  'WORKAHOLIC',
  'YOKEL',
  'YOUNGEST CHILD',
  'YOUXIA',
  'YUPPIE',
  'ZANNI',
  ],

  likes:[ 'ABANDONED BUILDINGS',
  'ACCESSORIES',
  'ACTING',
  'ADVENTURES',
  'AFFECTION',
  'ALCHEMY',
  'ALCOHOL',
  'ANIMALS',
  'ANTHROPOLOGY',
  'ANTIQUES',
  'AQUARIUMS',
  'ARCHERY',
  'ARCHITECTURE',
  'ARROGANCE',
  'ART',
  'ASTROLOGY',
  'ASTRONOMY',
  'BAGS',
  'BAKING/COOKING',
  'BAMBOO',
  'BEACHES',
  'BEEKEEPING',
  'BEER',
  'BEES AND BEEKEEPING',
  'BELLS',
  'BICYCLING',
  'BIRD WATCHING',
  'BIRTHDAYS',
  'BLACK COFFEE',
  'BLANKET FORTS',
  'BODY MODIFICATION',
  'BONFIRES',
  'BOOKS',
  'BOWLING',
  'BRIGHT LIGHTS',
  'BUGS',
  'BURNING FOOD',
  'BUTTERFLIES',
  'CAKE',
  'CALLIGRAPHY & TYPOGRAPHY',
  'CALM',
  'CAMPING',
  'CANDLES AND CANDLE-MAKING',
  'CANDY',
  'CANOEING OR KAYAKING',
  'CANOPY BEDS',
  'CARD GAMES',
  'CAVE EXPLORING',
  'CEMETERIES',
  'CHALK',
  'CHILDREN',
  'CHOCOLATE',
  'CLASSICAL MUSIC',
  'CLAY',
  'CLEANING',
  'CLIMBING',
  'CLOUDS',
  'CLOWNS',
  'CLUBBING',
  'CLUTTER',
  'COFFEE',
  'COFFEE MUGS',
  'COLD FRIES',
  'COLD SHOWERS',
  'COLLECTING',
  'COLORING',
  'COMEDY',
  'COMMUNITY',
  'COMPETITION',
  'COMPLAINING',
  'CONFIDENCE',
  'CONSPIRACY THEORIES',
  'COOKIE BUTTER',
  'COOKING',
  'COOL BREEZES',
  'COSMETOLOGY',
  'COZINESS',
  'CRACKED SKIN',
  'CRAFTS',
  'CRICKET SOUNDS',
  'CRITICISM',
  'CROCHETING OR KNITTING',
  'CROWDS',
  'CRYPTID/GHOST HUNTING',
  'CRYPTOZOOLOGY',
  'CRYSTALS',
  'CUDDLING',
  'CUTESY USERNAMES',
  'CYBERPUNK',
  'DANCE',
  'DANCING',
  'DANGER',
  'DARKNESS',
  'DARTS',
  'DEADLINES',
  'DEADPAN HUMOR.',
  'DEBATES',
  'DECORATING',
  'DIORAMAS',
  'DIVING',
  'DIY',
  'DIY REPAIR',
  'DOCUMENTARIES',
  'DOGS',
  'DOLLHOUSES AND DOLLHOUSE FURNITURE',
  'DOMINOES',
  'DRAMA',
  'DRAWING',
  'ESCAPE ROOMS',
  'ESSENTIAL OILS',
  'EXPLOSIVE… ANYTHING',
  'EXTRAVAGANT THINGS, CLOTHES, ETC.',
  'EXTREME COLD',
  'EXTREME HOT',
  'FACIAL HAIR',
  'FAIRY TALES',
  'FALCONRY',
  'FALL WEATHER',
  'FALLING',
  'FALLING LEAVES',
  'FAMILY',
  'FARMER\'S MARKETS',
  'FARMING',
  'FENCING/SWORD FIGHTING',
  'FICTION',
  'FIGHTING',
  'FIREPLACES',
  'FIREWORKS',
  'FISHING',
  'FITTED CLOTHING',
  'FLASH MOBS',
  'FLASHING LIGHTS',
  'FLAVORED COFFEE CREAMERS',
  'FLIRTING',
  'FLOWER PRESSING',
  'FLOWERS',
  'FLYING',
  'FOOD',
  'FORAGING',
  'FORESTS',
  'FOSSILS',
  'FOUL ODOR',
  'FRESH AIR',
  'FRESH LAUNDRY',
  'FULFILLMENT',
  'FUNERALS',
  'FUNGI',
  'GAMING',
  'GARDENING',
  'GARDENS/TOPIARIES',
  'GENEALOGY',
  'GLASS BLOWING',
  'GLITTER',
  'GLOWSTICKS',
  'GO ',
  'GOSSIP',
  'GREED',
  'GYMNASTICS',
  'GYOTAKU',
  'HAIL',
  'HAIR COLORING',
  'HAIR SALONS',
  'HAIR STYLING',
  'HANG GLIDING',
  'HANGNAILS',
  'HARDWOOD/CARPET FLOORS',
  'HATRED',
  'HATS',
  'HAUNTED HOUSES',
  'HAZING',
  'HEADACHES',
  'HEADPHONES',
  'HEAT AND HUMIDITY',
  'HEIGHTS',
  'HEROES',
  'HICCUPS',
  'HIDING',
  'HIKING',
  'HILLS',
  'HOLIDAYS',
  'HOMEWORK',
  'HOODIES',
  'HORSE RIDING',
  'HOSPITALS',
  'HOT AIR BALLOONS',
  'HOT BATHS',
  'HUNTING',
  'ICE CREAM',
  'ICE SCULPTURES',
  'IMPROV',
  'INCENSE',
  'INSTANT COFFEE',
  'INTERIOR DECORATING AND DESIGN',
  'INVENTING',
  'ITCHY SKIN',
  'JAZZ MUSIC',
  'JEWELRY',
  'JIGSAW PUZZLES',
  'JOURNALING',
  'JUDGMENT',
  'JUGGLING',
  'JUMP ROPE',
  'JUMP SCARES',
  'JUMPING',
  'KEEPING JOURNALS/DIARIES',
  'KETCHUP',
  'KITES',
  'KNICK-KNACKS',
  'KNIFE THROWING',
  'LAKES AND LAKESHORES',
  'LANDSCAPING',
  'LARGE GROUPS',
  'LARP',
  'LATE NIGHTS',
  'LAUGHTER',
  'LEARNING',
  'LEARNING LANGUAGES',
  'LEATHER',
  'LIBRARIES',
  'LIGHT BEER',
  'LIGHTNING',
  'LIMA BEANS',
  'LIVE MUSIC',
  'LOCKPICKING',
  'LOOSE, OVERSIZED CLOTHING',
  'LOUD NOISES',
  'LUKEWARM BEER',
  'LUKEWARM COFFEE',
  'LYING',
  'MAGIC',
  'MAKEOVERS',
  'MAKEUP',
  'MALICE',
  'MANICURE',
  'MANNEQUINS',
  'MAP MAKING',
  'MARTIAL ARTS',
  'MASSAGES',
  'MATH, SCIENCE, HISTORY, ETC.',
  'MATHEMATICS',
  'MAZES',
  'MEDITATION',
  'MESS',
  'METALWORKING',
  'METEOROLOGY',
  'MICROSCOPY',
  'MIST/FOG',
  'MIXING DRINKS',
  'MIXOLOGY (COCKTAILS)',
  'MODELING',
  'MONEY',
  'MOSHING',
  'MOUNTAINS',
  'MOVIES',
  'MULTITASKING',
  'MUSEUMS',
  'MUSHROOMS',
  'MUSIC',
  'MYTHOLOGY',
  'NAIL ART',
  'NAPPING',
  'NATURAL DISASTERS',
  'NATURE',
  'NECROMANCY',
  'NEEDLES',
  'NEW THINGS',
  'NON-FICTION',
  'NUMBERS',
  'NUMEROLOGY',
  'OBSCURE TRIVIA',
  'ONLINE GAMES',
  'OPEN MEADOWS',
  'OPEN SPACES',
  'OPEN WINDOWS',
  'OPPRESSION',
  'ORGANIZATION',
  'ORIGAMI',
  'PAINTBALL',
  'PAINTING',
  'PALEONTOLOGY',
  'PAPERCRAFTING (KEEPSAKE CARDS, ETC',
  'PAPERWORK',
  'PARKOUR',
  'PEEPS',
  'PHILOSOPHY',
  'PHOTOGRAPHY',
  'PIERCINGS (EARS, NOSE, NAVEL, ETC',
  'PINE CONES',
  'PIRATES',
  'PLANES',
  'PLANNING AND MAKING LISTS',
  'PLAYS / STAGE PRODUCTIONS',
  'POCKET WATCHES',
  'PODCASTS',
  'POEMS',
  'POI (PERFORMANCE ART)',
  'POLITICS',
  'POP MUSIC',
  'PORCELAIN DOLLS',
  'POSTAGE STAMPS',
  'POSTCARDS',
  'POSTERS',
  'POTTED PLANTS',
  'POTTERY',
  'PRAISE',
  'PRANKS',
  'PRESENTS',
  'PROGRAMMING',
  'PSYCHOLOGY',
  'PUBLIC SPEAKING',
  'PUNS',
  'PUZZLES',
  'PYROTECHNICS',
  'PYROTECHNICS / FIREWORKS',
  'QUIET',
  'QUILTING',
  'RAIN',
  'RECOGNITION',
  'REJECTION',
  'RENAISSANCE',
  'REPAIRING ITEMS',
  'REPETITION/ROUTINE',
  'RIDDLES',
  'RIVERS',
  'ROAD TRIPS',
  'ROBOTICS',
  'ROCK CLIMBING',
  'SAILING',
  'SAND CASTLES',
  'SANDALWOOD',
  'SANDCASTLES',
  'SCARECROWS',
  'SCARY MOVIES',
  'SCAVENGER HUNTS',
  'SCHOOL',
  'SCORN',
  'SCRAPBOOKING',
  'SCREAMING',
  'SCULPTING',
  'SEAFOOD',
  'SEASHELLS',
  'SHARP OBJECTS',
  'SHOES',
  'SHOPPING',
  'SHOWERS/BATHS',
  'SINGING',
  'SKATEBOARDING',
  'SKATING',
  'SKIING',
  'SMILES',
  'SMITHING',
  'SNAKES',
  'SNOBS',
  'SNORING',
  'SNOW',
  'SNOW GLOBES',
  'SNOWBOARDING',
  'SOAP CARVING',
  'SOAP MAKING',
  'SOCIAL EVENTS',
  'SPAS',
  'SPIDERS',
  'SPONTANEITY',
  'SPORTS',
  'STARRY NIGHTS',
  'STATIONARY',
  'STATUES',
  'STEAMPUNK',
  'STONE/GRAVESTONE RUBBING',
  'STONECRAFTING / STONE-CARVING',
  'STORM CHASING',
  'STORYTELLING',
  'STRATEGY (IN GENERAL)',
  'STREET FAIRES',
  'STRONG SCENTS',
  'STUFFED ANIMALS',
  'STYROFOAM',
  'SUCCESS',
  'SUDOKU',
  'SUN',
  'SUNRISES OR SUNSETS',
  'SURFING',
  'SURPRISES',
  'SWINGS',
  'TAROT',
  'TATTOOS',
  'TEA',
  'TEA SETS',
  'TECHNOLOGY',
  'THE MOON',
  'THE OCEAN',
  'THE RISING SUN',
  'THE STARS',
  'THE SUN',
  'THUNDERSTORMS',
  'TIGHT, FITTED CLOTHING',
  'TOPIARIES',
  'TRADITIONAL DISHES',
  'TRAINS',
  'TRAVELING',
  'TREASURE HUNTING',
  'TREES',
  'TRUST-BUILDING EXERCISES',
  'TULIPS',
  'TUTORING',
  'UGLY SWEATERS',
  'UMBRELLAS/PARASOLS',
  'VINTAGE STUFFS/DESIGNS',
  'VIOLENCE',
  'VOLUNTEERING',
  'WATER',
  'WEAPONS',
  'WHINING',
  'WILDFLOWERS',
  'WIND CHIMES',
  'WINDOW-SHOPPING',
  'WINE',
  'WINNING',
  'WITCHCRAFT',
  'WOODCRAFTING',
  'WOODWORKING',
  'WORD PUZZLES',
  'WRITING',
  'YO-YOS',
  'ZOOLOGY',
  'ZOOS',
  ],
};
